### ISSUE TITLE
inclexcl not in dsm.sys if inclexcl_local specified

### ISSUE THREAD

**Issue by ahuffman** [nosolutions/puppet-tsm#15]
I'm having trouble with the inclexcl params.  My dsm.sys is only specifying the InclExcl.local file instead of the 2 files.

Also, is there any way to hash the InclExcl.local with this module.  That would be a great new feature if not!

hieracode:
#TSM Backup Client Defaults
tsm::server_name: 'TSM1'
tsm::comm_method: 'TCPip'
tsm::tcp_port: '1500'
tsm::package_ensure: 'latest'
tsm::service_manage: true
tsm::service_ensure: 'running'
tsm::service_name: 'dsmsched'
tsm::service_script: '/etc/init.d/dsmsched'
tsm::tsm_pwd: '/etc/adsm/TSM.PWD'
tsm::initial_password: 'mypass'
tsm::config: '/opt/tivoli/tsm/client/ba/bin/dsm.sys'
tsm::config_opt: '/opt/tivoli/tsm/client/ba/bin/dsm.opt'
tsm::config_replace: true
tsm::inclexcl: '/opt/tivoli/tsm/client/ba/bin/InclExcl'
tsm::inclexcl_local: '/opt/tivoli/tsm/client/ba/bin/InclExcl.local'
tsm::inclexcl_replace: true
tsm::tcp_server_address: '9.9.9.9'
tsm::config_hash:
  errorlogname: '/opt/tivoli/tsm/client/ba/log/dsmerror.log'
  errorlogretention: '31 D'
  schedlogname: '/opt/tivoli/tsm/client/ba/log/dsmsched.log'
  schedlogretention: '31 D'
  nodename: "%{::hostname}"
  passwordaccess: 'generate'
  webports: '1551 1552'
  snapshotcachesize: '40'
  domain: 'all-local'
  resourceutilization: '9'
  memoryefficientbackup: 'yes'
tsm::config_opt_hash:
  Servername: 'TSM1'
  subdir: 'yes'

Generates:
* HEADER: This file was autogenerated by puppet.  Any changes to this
* HEADER: file are going to overwritten on the next puppet run.
* HEADER: If you would like to include local settings, use dsm.sys.local

* standard options
SErvername  TSM1
   COMMMethod            TCPip
   TCPPort               1500
   TCPServeraddress      9.9.9.9
   INCLExcl              /opt/tivoli/tsm/client/ba/bin/InclExcl.local

* additional options
   domain                all-local
   errorlogname          /opt/tivoli/tsm/client/ba/log/dsmerror.log
   errorlogretention     31 D
   inclexcl              /opt/tivoli/tsm/client/ba/bin/InclExcl.local
   memoryefficientbackup yes
   nodename              usfr-git
   passwordaccess        generate
   resourceutilization   9
   schedlogname          /opt/tivoli/tsm/client/ba/log/dsmsched.log
   schedlogretention     31 D
   snapshotcachesize     40
   webports              1551 1552

* settings included from dsm.sys.local (if any)

**Comment by tosmi** [comment]
please add the path to the default inclexcl to the config_hash:
```
tsm::config_hash:
  inclexcl: '/opt/tivoli/tsm/client/ba/bin/InclExcl'
```
i have to confess this is a little bit confusing, maybe some cleanup is required. i've included the directive for inclexcl.local in the standard option section because we will always generate inclexcl.local. looking at the code, it seems to me the right way is to also add

```
InclExcl ../InclExcl
```
to the standard options. i'll going to review the code tomorrow, maybe a bugfix release is required.

thanks for reporting
toni

**Comment by ahuffman** [comment]
Thanks, not sure if you missed the other question about hashing the InclExcl.local file so we can store the server's local InclExcl in hiera (which would be very convenient.)  That may be a feature request if not currently capable.

**Comment by tosmi** [comment]
ah, ok. good idea. i'm going to add an inclexcl.hiera file. the idea behind inclexcl.local is to allow local additions to the global inclexcl config.

thanks
toni

**Comment by ahuffman** [comment]
That would be a great management improvement!  Looking forward to it.  We usually backup specific areas of our system, and not just an entire server's volumes.   This will really help out in that scenario.

**Comment by ahuffman** [comment]
I removed the inclexcl parameter from the main tsm class and into the config_hash as suggested.  This is what it generates for me.

* HEADER: This file was autogenerated by puppet.  Any changes to this
* HEADER: file are going to overwritten on the next puppet run.
* HEADER: If you would like to include local settings, use dsm.sys.local

* standard options
SErvername  TSM1
   COMMMethod            TCPip
   TCPPort               1500
   TCPServeraddress      9.9.9.9
   INCLExcl              /opt/tivoli/tsm/client/ba/bin/InclExcl.local

* additional options
   domain                all-local
   errorlogname          /opt/tivoli/tsm/client/ba/log/dsmerror.log
   errorlogretention     31 D
   inclexcl              /opt/tivoli/tsm/client/ba/bin/InclExcl
   memoryefficientbackup yes
   nodename              myserver
   passwordaccess        generate
   resourceutilization   9
   schedlogname          /opt/tivoli/tsm/client/ba/log/dsmsched.log
   schedlogretention     31 D
   snapshotcachesize     40
   webports              1551 1552

* settings included from dsm.sys.local (if any)



Just a quick question as I've never used multiple inclexcl files before.  Will it load the first inclexcl and then combine with the inclexcl.local settings, or some other behavior.  Sorry if this is outside of the scope of the module, but I'm not a TSM admin so I just want to make sure I understand the behavior so I can communicate with my team.

**Comment by tosmi** [comment]
yes, thats whats happening as far as i know. it combines all inclexcl files into a single list. the documentation is very unspecific:

http://www-01.ibm.com/support/knowledgecenter/SSGSG7_7.1.2/com.ibm.itsm.client.doc/r_opt_inclexcl.html?lang=en

<quote>Multiple inclexcl statements are permitted. However, you must specify this option for each include-exclude file.</quote>

hth
toni

**Comment by tosmi** [comment]
is it ok from you side to close this issue for now? i've create a another ticket for the inclexcl.hiera enhancement. hopefully i find the time to implement this in the next few weeks.

toni
