### ISSUE TITLE
add inclexcl.hiera hash (like config_hash) so we can manage inclexcl entries via hiera

### ISSUE THREAD

**Issue by tosmi** [nosolutions/puppet-tsm#16]

**Comment by bschonec** [comment]
@tosmi , have you made the code changes or pull request for this?  I'm about to do the same but don't want to duplicate efforts.

**Comment by tosmi** [comment]
no, this is currently not implemented. a pull request would be great. please also add some rspec tests for this.

thanks
toni

**Comment by bschonec** [comment]
@tosmi Well, I know nothing (yet) about writing tests.  I can't even get the master branch to pass the existing tests, let alone anything *I* may add.  Would you be so kind as to fork the master and give it a TravisCI runthrough?

**Comment by tosmi** [comment]
i'll look into that tomorrow. we can work on the test together, just try to fork the repo, create a feature branch (e.g. inclexclhiera) and play around with the tests.

how did you try to run the tests?

**Comment by bschonec** [comment]
I'll work on that this week.  I did finally get the *existing* tests to succeed on my server.  It's writing new tests that confound me.  I'm not a developer by any stretch.

**Comment by bschonec** [comment]
I hope I don't make too much of a fool of myself for #46

**Comment by tosmi** [comment]
thank for the pr. i'm going to look into it over the next days.
