### ISSUE TITLE
Managing dsmcad as a service

### ISSUE THREAD

**Issue by ahuffman** [nosolutions/puppet-tsm#18]
It would be nice to have an option to manage dsmcad as a service.  This would of course be an improvement request.

**Comment by tosmi** [comment]
ok, i am going to look into this as soon as i find the time. pull requests are also always welcome :-)

**Comment by tosmi** [comment]
ENOTIME, pull requests are still welcome

**Comment by tosmi** [comment]
fixed by pull request #43.
