### ISSUE TITLE
Puppet master reporting issue with config_opt_hash (deprecated)

### ISSUE THREAD

**Issue by ahuffman** [nosolutions/puppet-tsm#19]
Getting this on my puppet master:
Jun 12 13:01:17 mypuppetmaster puppet-master[2165]: Variable access via 'config_opt_hash' is deprecated. Use '@config_opt_hash' instead. template[/etc/puppet/environments/production/modules/tsm/templates/dsm.opt.erb]:6

**Comment by tosmi** [comment]
thanks for the report. i'll try to come up with a fix for this asap.
