### ISSUE TITLE
Setting initial password

### ISSUE THREAD

**Issue by janorn** [nosolutions/puppet-tsm#25]
Hi,

In our solaris environment we can't get dsmc set password to work. However if you just do dsmc we get prompted for the password and all is fine. After this initial config dsmc set password works fine....

Any idea?

**Comment by tosmi** [comment]
hm, what happend after you got prompted for the password? did you enter the password? what's you password setting in dsm.sys? setting the password only works if you add 'PASSWORDAccess generate' in dsm.sys. we use 'tsm::config_hash' for this purpose.

**Comment by tosmi** [comment]
if this does not help, please post your dsm.sys and the output of `puppet agent -t --debug` (maybe use a github gist for this). any settings you specified via hiera, foreman or in a profile would also be useful.

thanks for the report
toni

**Comment by janorn** [comment]
```
* HEADER: This file was autogenerated by puppet.  Any changes to this
* HEADER: file are going to overwritten on the next puppet run.
* HEADER: If you would like to include local settings, use dsm.sys.local

* standard options
SErvername  tsmsrv1
   COMMMethod            TCPip
   TCPPort               1500
   TCPServeraddress      tsm-server
   INCLExcl              /opt/tivoli/tsm/client/ba/bin/InclExcl.local

* additional options
   errorlogname          /var/log/dsmerror.log
   errorlogretention     31 D
   inclexcl              /opt/tivoli/tsm/client/ba/bin/InclExcl
   nodename              clientmachine
   passwordaccess        generate
   schedlogname          /var/log/dsmsched.log
   schedlogretention     5 D

* settings included from dsm.sys.local (if any)
```

```
Debug: Exec[generate-tsm.pwd](provider=posix): Executing 'dsmc set password tsmadmin 7c6db96752b0ff4f32bfbe8bc8f0042244b6d319f38af73c'
Debug: Executing 'dsmc set password tsmadmin 7c6db96752b0ff4f32bfbe8bc8f0042244b6d319f38af73c'
Notice: /Stage[main]/Tsm::Service/Exec[generate-tsm.pwd]/returns: ANS5844E Unable to update password.
Notice: /Stage[main]/Tsm::Service/Exec[generate-tsm.pwd]/returns: ANS0102W Unable to open the message repository /opt/tivoli/tsm/client/ba/bin/EN_GB/dsmclientV3.cat. The American English repository will be used instead.
Notice: /Stage[main]/Tsm::Service/Exec[generate-tsm.pwd]/returns: IBM Tivoli Storage Manager
Notice: /Stage[main]/Tsm::Service/Exec[generate-tsm.pwd]/returns: Command Line Backup-Archive Client Interface
Notice: /Stage[main]/Tsm::Service/Exec[generate-tsm.pwd]/returns:   Client Version 7, Release 1, Level 1.0 
Notice: /Stage[main]/Tsm::Service/Exec[generate-tsm.pwd]/returns:   Client date/time: 02/11/2015 10:45:09
Notice: /Stage[main]/Tsm::Service/Exec[generate-tsm.pwd]/returns: (c) Copyright by IBM Corporation and other(s) 1990, 2014. All Rights Reserved.
Error: dsmc set password tsmadmin 7c6db96752b0ff4f32bfbe8bc8f0042244b6d319f38af73c returned 12 instead of one of [0]
Error: /Stage[main]/Tsm::Service/Exec[generate-tsm.pwd]/returns: change from notrun to 0 failed: dsmc set password tsmadmin 7c6db96752b0ff4f32bfbe8bc8f0042244b6d319f38af73c returned 12 instead of one of [0]
Notice: /Stage[main]/Tsm::Service::Solaris/Service[tsm]: Dependency Exec[generate-tsm.pwd] has failures: true
Warning: /Stage[main]/Tsm::Service::Solaris/Service[tsm]: Skipping because of failed dependencies
```

**Comment by janorn** [comment]
Solaris 11, x86 if that makes any difference.

**Comment by tosmi** [comment]
hm, and running 'dsmc set password tsmadmin 7c6db96752b0ff4f32bfbe8bc8f0042...' on the command line works? i'm really not a tsm expert, but i would make sure that the tsm node 'clientmachine'  has $initial_password set (e.g. 'tsmadmin' in the your case).

if you are sure running the same command works on the console, maybe there's a difference in the environment (wild guess) between running 'dsmc set password' on the console and when the puppet agent tries to execute it. if running 'dsmc set password' prompts for the password, maybe thats a hint that the initial password 'tsmadmin' is not correct.

not really helpful, i know, but we always had this problem if the initial node password was not set to $initial_password.

**Comment by janorn** [comment]
No not at all. I get a similar error as in the puppet log. But if I invoke just type dsmc and go into the interactive part I will get prompted to login. This will create the pw cache which the exec checks for so the rest of the run will work fine. However now I can do dsmc set password oldpw newpw.

I have no idea why it works when the pw cache exists.

**Comment by janorn** [comment]
```
# dsmc set password tsmadmin randompw
ANS0102W Unable to open the message repository /opt/tivoli/tsm/client/ba/bin/EN_GB/dsmclientV3.cat. The American English repository will be used instead.
IBM Tivoli Storage Manager
Command Line Backup-Archive Client Interface
  Client Version 7, Release 1, Level 1.0 
  Client date/time: 02/11/2015 20:32:18
(c) Copyright by IBM Corporation and other(s) 1990, 2014. All Rights Reserved.

ANS5844E Unable to update password.
```

**Comment by tosmi** [comment]
sorry, the module expects that dsmc set password works. maybe it has to do with the warning message 'could not open message repo'. as fair as i remember reinstalling the tsm package solved this for us (under redhat). maybe you could as someone from ibm (open a case?).

toni

**Comment by janorn** [comment]
This turned out to be an issue with FQDN. I.e tsm server had FQDN names while the dsm.sys only hade non qualified names. Fixing this resolved the set password issue.
