### ISSUE TITLE
Concat dependency update

### ISSUE THREAD

**Issue by rndmh3ro** [nosolutions/puppet-tsm#40]
This modules requires the concat module in version <2.1.0, as specified here:
https://github.com/nosolutions/puppet-tsm/blob/master/metadata.json#L84-L87

In the .fixtures.yml (https://github.com/nosolutions/puppet-tsm/blob/master/.fixtures.yml#L6-L8) however concat version 2.1.0 is specified.

I removed the version dependency in the metadata.json and everything was still working for me when using the tsm-module. So i propose to remove the constraint on the concat module.

**Comment by tosmi** [comment]
ok, thanks for the report. i've just pinned the module to conca < 3.0, which should be save.
