### ISSUE TITLE
non-quoted AIX makes tests fail

### ISSUE THREAD

**Issue by Zugschlus** [nosolutions/puppet-tsm#41]
Hi,

I am pretty new to github and to puppet tests, so please accept my apologies if I have violated some etiquette by filing this issue. I am not sure whether it would actually help to file a merge request for the suggested one-line fix.

In current HEAD and the last release tag, the tests that are invoked by rake spec fail in the AIX parts. I guess that this is caused by the string AIX not being quoted in line 241 of manifests/init.pp - obviously unquoted all caps strings are an issue at this place. replacing AIX with 'AIX' makes the tests pass again.

Greetings
Marc

**Comment by tosmi** [comment]
this should be fixed in current head, thanks for the report!
