### ISSUE TITLE
Paramaterize or Hashify Inclexcl file

### ISSUE THREAD

**Issue by bschonec** [nosolutions/puppet-tsm#47]
For me, the Red Hat InclExcl file is a bit too restrictive.  I realize that I can create a new InclExcl file and use the variable $inclexcl_source  to point to a new file but it would be nicer to be able to specify what I want contained in Inclexcl rather than creating a new file.

Perhaps it would be better to make both Inclexcl and Inclexcl.local a defined type?  They're essentially identical and making them a defined type would allow any number of InclExcl files to be created/included.

Creating a defined type would necessarily cause backwards incompatibility whereas templatizing the files would not.

Thoughts?

**Comment by tosmi** [comment]
this should be fixed with pull request #48. i'll try to come up with a new release asap
